### idea ye h k regression me ham apny numerical vairbales ko transfrom kar k check karty h kya wo targes sy zyada behtar correlated hen ya nahi, yahan me ny sqrt, log2, log10, and polynomial (till degree 4) tak check kar k sab sy zyada jo version correlated h target k sath us variable ko us me convert kar dya h

In [90]:
import pandas as pd
import numpy as np

In [91]:
df = pd.read_csv("data.csv")

In [105]:
num_vars = df.dtypes[(df.dtypes == 'int64') | (df.dtypes == 'float64')].index
df_num = df[num_vars]
y_train = df_num['RentAmount']
df_num.head()

,Unnamed: 0,applicationnumber,loantype,LoanAmount,EstablishedSinceMonths,CurrentAddressSinceMonths,DocumentCharge,EMI,InterestRate,InsuranceRate,InsuranceAmount,AccomodationType,ResidenceType,RentAmount,OtherLoanBank,NoOfDependents,NetBusinessIncome,NetDisposableIncome,30 DPDs Instance,DPD30
0,1,321071.0,8,0.20,0.001835,0.000000,0.138889,0.099525,0.75,0.0,0.000000,0,0,0.000000,0,0.072165,0.997012,30600.0,1,1
1,2,240464.0,8,0.20,0.001101,0.024490,0.092593,0.102107,1.00,1.1,0.187190,0,0,0.000000,0,0.051546,0.996989,18215.0,8,1
2,3,288229.0,8,0.60,0.005138,0.059592,0.685185,0.257851,0.75,0.0,0.000000,0,0,0.000000,0,0.061856,0.997007,20800.0,0,0
3,4,206150.0,8,0.60,0.002202,0.008571,0.462963,0.257940,0.75,1.1,0.368105,0,1,0.041667,0,0.020619,0.997023,26570.0,0,0
4,5,256515.0,8,0.76,0.006239,0.024490,0.462963,0.261799,0.75,1.1,0.582484,0,0,0.000000,0,0.030928,0.997021,29250.0,0,0

In [106]:
df_num.columns

Index(['Unnamed: 0', 'applicationnumber', 'loantype', 'LoanAmount',
       'EstablishedSinceMonths', 'CurrentAddressSinceMonths', 'DocumentCharge',
       'EMI', 'InterestRate', 'InsuranceRate', 'InsuranceAmount',
       'AccomodationType', 'ResidenceType', 'RentAmount', 'OtherLoanBank',
       'NoOfDependents', 'NetBusinessIncome', 'NetDisposableIncome',
       '30 DPDs Instance', 'DPD30'],
      dtype='object')

In [107]:
vars_to_modifiy = ['','','',''] # specify which variables you need to modify
df_for_modification = df_num[vars_to_modifiy]
most_plausibles = []
for column in df_for_modification.columns:
    orignal = df_for_modification[column]
    sq = np.sqrt(df_for_modification[column])
    lg10 = np.log10(df_for_modification[column]+0.0000001)
    lg2 = np.log2(df_for_modification[column]+0.0000001)
    pol2 = df_for_modification[column] ** 2
    pol3 = df_for_modification[column] ** 3
    pol4 = df_for_modification[column] ** 4
    minn = []
    for i in ['sq', 'lg10', 'lg2', 'pol2', 'pol3', 'pol4', 'orignal']:
        minn.append((i,np.corrcoef(eval(i), y_train).min()))
    most_plausibles.append((column, sorted(dict(minn), key=(lambda key:dict(minn)[key]), reverse=True)[0]))

In [111]:
for i in most_plausibles:
    if i [1] ==  'sq':
        df[i[0]] = np.sqrt(df[i[0]])
    elif i[1] == 'lg10':
        df[i[0]] = np.log10(df[i[0]]+ 0.0000001)
    elif i[1] == 'lg2':
        df[i[0]] = np.log2(df[i[0]]+ 0.0000001)
    elif i[1] == 'pol2':
        df[i[0]] = df[i[0]] ** 2
    elif i[1] == 'pol3':
        df[i[0]] = df[i[0]] ** 3
    elif i[1] == 'pol4':
        df[i[0]] = df[i[0]] ** 4
    elif i[1] == 'orignal':
        pass

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in log10
  """

In [113]:
df[vars_to_modifiy]

        InsuranceAmount  EstablishedSinceMonths  LoanAmount  InterestRate
0              0.000000                     NaN    0.668740  1.002260e-02
1              0.657764                     NaN    0.668740  1.000000e+00
2              0.000000                     NaN    0.880112  1.002260e-02
3              0.778920                     NaN    0.880112  1.002260e-02
4              0.873617                     NaN    0.933691  1.002260e-02
5              0.770771                     NaN    0.880112  1.002260e-02
6              0.858009                     NaN    1.000000  1.801561e-06
7              0.000000                     NaN    1.000000  1.801561e-06
8              0.000000                     NaN    1.000000  1.525879e-05
9              0.657535                     NaN    0.668740  1.000000e+00
10             0.000000                     NaN    0.727427  1.002260e-02
11             0.000000                     NaN    0.880112  1.002260e-02
12             0.000000                     NaN    0.668740  1.000000e+00
13             0.621858                     NaN    0.588566  1.000000e+00
14             0.612972                     NaN    0.588566  1.000000e+00
15             0.000000                     NaN    0.668740  1.000000e+00
16             0.831905                     NaN    0.957348  1.002260e-02
17             0.000000                     NaN    0.668740  1.002260e-02
18             0.663880                     NaN    0.699927  1.180671e-01
19             0.686589                     NaN    0.668740  1.000000e+00
20             0.612972                     NaN    0.588566  1.000000e+00
21             0.000000                     NaN    0.880112  1.002260e-02
22             0.000000                     NaN    0.727427  1.002260e-02
23             0.648139                     NaN    0.668740  1.000000e+00
24             0.655688                     NaN    0.668740  3.607231e-02
25             0.000000                     NaN    0.668740  1.002260e-02
26             0.000000                     NaN    0.668740  1.002260e-02
27             0.000000                     NaN    0.668740  1.000000e+00
28             0.612972                     NaN    0.588566  1.000000e+00
29             0.612972                     NaN    0.588566  3.607231e-02
...                 ...                     ...         ...           ...
255896         0.770771                     NaN    0.880112  1.002260e-02
255897         0.000000                     NaN    1.000000  1.801561e-06
255898         0.923654                     NaN    1.000000  1.002260e-02
255899         0.000000                     NaN    1.000000  1.002260e-02
255900         0.657535                     NaN    0.668740  1.000000e+00
255901         0.000000                     NaN    0.727427  1.002260e-02
255902         0.000000                     NaN    1.000000  1.002260e-02
255903         0.657994                     NaN    0.668740  1.000000e+00
255904         0.000000                     NaN    0.814448  5.421011e-04
255905         0.770771                     NaN    0.880112  1.002260e-02
255906         0.971198                     NaN    1.000000  1.529327e-07
255907         0.658681                     NaN    0.668740  1.000000e+00
255908         0.923654                     NaN    1.000000  1.002260e-02
255909         0.765143                     NaN    0.774597  1.180671e-01
255910         0.000000                     NaN    0.814448  5.421011e-04
255911         0.657535                     NaN    0.668740  1.000000e+00
255912         0.000000                     NaN    0.668740  3.607231e-02
255913         0.770771                     NaN    0.880112  1.002260e-02
255914         0.657535                     NaN    0.668740  1.000000e+00
255915         0.658681                     NaN    0.668740  1.000000e+00
255916         0.000000                     NaN    0.668740  1.180671e-01
255917         0.778920                     NaN    0.880112  1.002260e-02
255918         0.000000                     NaN    0.880112  1.002260e-02
255919         0.823608                     NaN    0.945742  1.002260e-02
255920         0.713984                     NaN    0.774597  1.180671e-01
255921         0.770771                     NaN    0.880112  1.002260e-02
255922         0.000000                     NaN    0.880112  1.002260e-02
255923         0.770771                     NaN    0.880112  1.002260e-02
255924         0.770771                     NaN    0.880112  1.002260e-02
255925         0.000000                     NaN    1.000000  1.002260e-02

[255926 rows x 4 columns]